CREATE TABLE chemicals (
	SRS_ID INT PRIMARY KEY NOT NULL,
	CHEMICAL VARCHAR(255) NOT NULL
);

CREATE TABLE industry (
	INDUSTRY_SECTOR_CODE INT PRIMARY KEY NOT NULL,
	INDUSTRY_SECTOR VARCHAR(255) NOT NULL
);

CREATE TABLE tribes (
	DOCUMENT_NUMBER BIGINT PRIMARY KEY NOT NULL,
	TRIBAL_LAND VARCHAR(255)
);

CREATE TABLE tri_data (
	DOCUMENT_NUMBER BIGINT PRIMARY KEY NOT NULL,
	FACILITY_NAME VARCHAR(255),
	PARENT_COMPANY_NAME VARCHAR(255),
	STATE VARCHAR(255),
	REGION VARCHAR(255),
	LATITUDE NUMERIC,
	LONGITUDE NUMERIC,
	FEDERAL_FACILITY VARCHAR(255),
	TRIBAL_LAND VARCHAR(255),
	INDUSTRY_SECTOR_CODE INT,
	SRS_ID INT,
	METAL_CATEGORY VARCHAR(255),
	CARCINOGEN VARCHAR(255),
	ON_SITE_RELEASE_TOTAL NUMERIC,
	OFF_SITE_RELEASE_TOTAL NUMERIC,
	OFF_SITE_RECYCLED_TOTAL NUMERIC,
	ONE_TIME_RELEASE NUMERIC,
	UNIT_OF_MEASURE VARCHAR(255),
	FOREIGN KEY (INDUSTRY_SECTOR_CODE) REFERENCES industry(INDUSTRY_SECTOR_CODE),
	FOREIGN KEY (SRS_ID) REFERENCES chemicals(SRS_ID)
);